# Generated by Django 2.0.6 on 2018-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QFXTickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowShowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_link', models.CharField(max_length=255)),
            ],
        ),
    ]
